complete -c easyeffects -s b -l bypass -d "Global bypass. 1 to enable, 2 to disable and 3 to get status"
complete -c easyeffects -l gapplication-service -d "Enter GApplication service mode (use from D-Bus service files)"
complete -c easyeffects -l help-all -d "Show all help options"
complete -c easyeffects -l help-gapplication -d "Show GApplication options"
complete -c easyeffects -s h -l help -d "Show help options"
complete -c easyeffects -s l -l load-preset -d "Load a preset. Example: easyeffects -l music"
complete -c easyeffects -s p -l presets -d "Show available presets."
complete -c easyeffects -s q -l quit -d "Quit EasyEffects. Useful when running in service mode."
complete -c easyeffects -s r -l reset -d "Reset EasyEffects."
complete -c easyeffects -s w -l hide-window -d "Hide the Window."
