complete -c lobster -f -s 'c' -l 'continue' -d 'continue from history'
complete -c lobster -F -s 'd' -l 'download' -d 'download video to optional directory [default: $CWD]'
complete -c lobster -f -s 'e' -l 'edit' -d 'edit config'
complete -c lobster -f -s 'h' -l 'help' -d 'show help text'
complete -c lobster -f -s 'i' -l 'image-preview' -d 'show image previews [requires: ueberzugpp]'
complete -c lobster -f -s 'j' -l 'json' -d 'output json with video & subtitle links, referrers etc.'
complete -c lobster -f -r -s 'l' -l 'language' -d 'specify subtitle language [default: english]'
complete -c lobster -f -l 'rofi' -d 'use rofi as selector'
complete -c lobster -f -l 'dmenu' -d 'use dmenu as selector'
complete -c lobster -f -l 'external-menu' -d 'use an external command as a selector'
complete -c lobster -f -s 'p' -l 'provider' -d '[Upcloud, Vidcloud] [default: UpCloud]'
complete -c lobster -f -r -s 'q' -l 'quality' -d 'specify quality [default: 1080p]' -a '480p,720p,1080p,2160p'
complete -c lobster -f -l 'quiet' -d 'suppress output from mpv when playing video'
complete -c lobster -f -s 'r' -l 'recent' -d 'select recently added movies or tv [default: movies]' -a 'movies,tv'
complete -c lobster -f -s 's' -l 'syncplay' -d 'use Syncplay to watch with friends'
complete -c lobster -f -s 't' -l 'trending' -d 'select from trending movies and tv'
complete -c lobster -f -s 'u' -s 'U' -l 'update' -d 'update the script'
complete -c lobster -f -s 'v' -s 'V' -l 'version' -d 'show version'
complete -c lobster -f -s 'x' -l 'debug' -d 'enable debug mode [stdout and /tmp/lobster.log]'
