#!/bin/sh

userresources=$HOME/.config/.Xresources
usermodmap=$HOME/.config/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xrandr --output virtual-1

/usr/bin/clipmenud &                  # clipboard history daemon
/usr/lib/kdeconnectd &                # kdeconnect daemon
/usr/bin/pcmanfm --daemon-mode &      # file-manager daemon
/usr/bin/picom &                      # window opacity / blur
/usr/bin/redshift &                   # bluelight filter
/usr/bin/udiskie -An --terminal=lf &  # notif for mountable drives
/usr/bin/xbanish &                    # hide mouse when typing
~/.local/bin/map-keys &               # map caps to ctrl/esc
~/.local/bin/trackball-speed &        # set trackball speed

# randomized wallpapers
/usr/bin/feh --randomize --bg-scale --no-fehbg ~/media/pictures/nature/ &

# startup sound
/usr/bin/mpv --no-config --no-video ~/.config/sounds/ps2.flac &

xhost +SI:localuser:$USER

exec spectrwm
