#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xrandr --output=virtual-1

clipcatd &                     # clip history daemon
/usr/lib/kdeconnectd &         # kdeconnect daemon
mons -a &                      # external display daemon
pcmanfm --daemon-mode &        # file-manager daemon
picom &                        # window opacity / blur
redshift &                     # bluelight filter
udiskie -An &                  # notify + mount usbs
xbanish &                      # hide mouse when typing
~/.local/bin/map-keys &        # map caps to ctrl/esc
~/.local/bin/trackball-speed & # set trackball speed

xhost +SI:localuser:$USER

exec spectrwm
