#!/bin/sh

export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
userresources="$CONFIG_DIR/X11/Xresources"
usermodmap="$CONFIG_DIR/.Xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f "$sysresources" ]; then
	xrdb -merge "$sysresources"
fi
if [ -f "$sysmodmap" ]; then
	xmodmap "$sysmodmap"
fi
if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xrandr --output eDP-1

alacritty --daemon &           # alacritty daemon
caffeine &                     # inhibit sleep w/ media
dunst &                        # notification daemon
/usr/lib/kdeconnectd &         # kdeconnect daemon
picom &                        # window opacity / blur
redshift &                     # bluelight filter
xbanish &                      # hide mouse when typing
xss-lock -- xlock &            # lock on sleep etc.
~/.local/bin/trackball-speed & # set trackball speed

xhost +SI:localuser:$USER
