jsx = "react"
jsxFactory = "h"
jsxFragment = "Fragment"
jsxImportSource = "react"
telemetry = false

[test]
coverage = true
coverageThreshold = { line = 0.7, function = 0.8, statement = 0.9 }
coverageReporter  = ["lcov"]

[install]
minimumReleaseAge = 604800
