backend = "glx"
blur-background = true
blur-method = "dual_kawase"
blur-strengh = 1
detect-transient = true
fade = false
inactive-dim = 0.1
inactive-opacity = 0.9

focus-exclude = [
  "class_g = 'xlock'",
  "class_g = 'zoom'"
];
wintypes:
{
  combo         = { focus = false }
  dialog        = { focus = false }
  dropdown_menu = { focus = false }
  menu          = { focus = false }
  popup_menu    = { focus = false }
  tooltip       = { focus = false }
  utility       = { focus = false }
}
