backend = "glx"
blur-background = true
blur-method = "dual_kawase"
blur-strengh = 1
detect-transient = true
fade = false
glx-no-rebind-pixmap = true
glx-no-stencil = true
inactive-dim = 0.1
inactive-opacity = 0.9

focus-exclude = [
  "class_g = 'xlock'",
  "name = 'Peek'",
  "name = 'Picture-in-Picture'",
]

wintypes = {
  combo         = { shadow = false; blur-background = false }
  dialog        = { shadow = false; blur-background = false }
  dropdown_menu = { shadow = false; blur-background = false }
  menu          = { shadow = false; blur-background = false }
  popup_menu    = { shadow = false; blur-background = false }
  tooltip       = { shadow = false; blur-background = false }
  utility       = { shadow = false; blur-background = false }
}
