backend="glx";
inactive-dim=0.3;
focus-exclude = [
  "name = 'Peek'",
  "class_g = 'xlock'",
];
wintypes:
{
  combo         = { focus = false }
  dialog        = { focus = false }
  dropdown_menu = { focus = false }
  menu          = { focus = false }
  popup_menu    = { focus = false }
  tooltip       = { focus = false }
  utility       = { focus = false }
}
