model = "gpt-5.6-sol"
model_reasoning_effort = "high"

[features]
plugin_hooks = true
hooks = true

[tui.model_availability_nux]
"gpt-5.6-sol" = 4

[marketplaces.context-mode]
last_updated = "2026-07-21T17:36:02Z"
last_revision = "3e530617e7ddee634b943ba99aa3aa08185cf0fd"
source_type = "git"
source = "https://github.com/mksglu/context-mode.git"

[marketplaces.ponytail]
last_updated = "2026-07-19T22:59:01Z"
last_revision = "16f29800fd2681bdf24f3eb4ccffe38be3baec6b"
source_type = "git"
source = "https://github.com/DietrichGebert/ponytail.git"

[plugins."ponytail@ponytail"]
enabled = true

[plugins."context-mode@context-mode"]
enabled = true

[hooks.state]

[hooks.state."ponytail@ponytail:hooks/claude-codex-hooks.json:session_start:0:0"]
trusted_hash = "sha256:5f81d38f47448a1581c08ec877e044d9e04dd6f814dce3f2671f7a8edadd719b"

[hooks.state."ponytail@ponytail:hooks/claude-codex-hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:6a6f42bc3b58d6262db38bfd74d7f340fcca2b09cdb134aad365063f0bfefca4"

[hooks.state."ponytail@ponytail:hooks/claude-codex-hooks.json:subagent_start:0:0"]
trusted_hash = "sha256:1423b56c1322f96c8f74c51c1e7ae9a047b904c1fa43ee9165d462fd7a6e70ef"

[hooks.state."context-mode@context-mode:.codex-plugin/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:56da0c4249dc7af048f42ae458fb83931926a8af41ec6fab5ae819ff3a8c83ae"

[hooks.state."context-mode@context-mode:.codex-plugin/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:0d237345f8d46110d36cd0ef08e79b55fa151a07691dee36d492aa6f64bc0efd"
enabled = false

[hooks.state."context-mode@context-mode:.codex-plugin/hooks.json:pre_compact:0:0"]
trusted_hash = "sha256:ac1f9e5eb71ca262492150381d8f078b897056fc691f9973fc56d7b1b402e648"

[hooks.state."context-mode@context-mode:.codex-plugin/hooks.json:session_start:0:0"]
trusted_hash = "sha256:a6cc6a322d0931bdd68a5969e523cd71e6eedccab4850e8996c8948311173618"

[hooks.state."context-mode@context-mode:.codex-plugin/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:114549c484c131b94782d3424527dd1042d48bc3a8616a11299acdf60b112572"

[hooks.state."context-mode@context-mode:.codex-plugin/hooks.json:stop:0:0"]
trusted_hash = "sha256:9205c1763e40c0256ab334e2e96c037c1cdf5b8bfaddba31ed19d93d3388586a"

[notice]
hide_rate_limit_model_nudge = true
