[v1]
"cargo-binstall 1.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-nextest 0.9.140 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-update 22.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"caser-cli 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/caser)" = ["caser"]
"colorcol 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/colorcol-rs)" = ["colorcol"]
"cpz 3.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cpz"]
"depsguard 0.1.40 (registry+https://github.com/rust-lang/crates.io-index)" = ["depsguard"]
"grug 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/grug)" = ["grug"]
"hexapoda 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexapoda"]
"hors 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["hors"]
"httm 0.50.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["httm"]
"kak-ansi-rs 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/kak-ansi-rs)" = ["kak-ansi-filter"]
"kak-lsp 21.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["kak-lsp"]
"kak-popup 0.6.3-beta (path+file:///home/sugimoto/.config/kak/bundle/popup.kak)" = ["kak-popup"]
"kak-rainbow-rs 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/kak-rainbow-rs)" = ["kak-rainbow-rs"]
"kak-tree-sitter 3.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["kak-tree-sitter"]
"kakship 0.2.9 (path+file:///home/sugimoto/.config/kak/bundle/kakship)" = ["kakship"]
"ktsctl 3.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["ktsctl"]
"mise 2026.7.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["mise"]
"protonup-rs 0.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["protonup-rs"]
"putzen-cli 3.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["putzen"]
"rkak_easymotion 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/reasymotion)" = ["rkak_easymotion"]
"rmz 3.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rmz"]
"rustywind 0.25.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustywind"]
"sccache 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
"seetui 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["seetui"]
"thesauromatic 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["thesauromatic"]
"topgrade 17.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"vopono 0.10.18 (registry+https://github.com/rust-lang/crates.io-index)" = ["vopono"]
"vortix 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["vortix"]
