[v1]
"archlinux-inputs-fsck 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["archlinux-inputs-fsck"]
"atac 0.23.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["atac"]
"attractorr 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["attractorr"]
"baijia-suo 0.1.0 (path+file:///home/sugimoto/repos/baijia-suo)" = ["baijia-suo"]
"binsider 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["binsider"]
"bottom 0.12.3 (git+https://github.com/ClementTsang/bottom#6daf7ebd3f88170e553a3220383f50af91b9885d)" = ["btm"]
"cargo-binstall 1.19.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-fix 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fix"]
"cargo-nextest 0.9.133 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-run-bin 1.7.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bin"]
"cargo-trend 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-trend"]
"cargo-update 20.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-vcpkg 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-vcpkg"]
"caser-cli 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/caser)" = ["caser"]
"conceal 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cnc",
    "conceal",
]
"cpz 3.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cpz"]
"crabz 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["crabz"]
"dedoc 0.2.9 (git+https://github.com/toiletbril/dedoc#616eee3d0875f1bd5cf1ae331fd24074c100bfd1)" = ["dedoc"]
"diffsitter 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "diffsitter",
    "diffsitter-utils",
    "diffsitter_completions",
]
"dotenv-linter 4.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dotenv-linter"]
"fclones 0.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fclones"]
"fish-manpage-completions 0.1.0 (git+https://github.com/rust-dc/fish-manpage-completions#d927605f1d2562e7f65c1d49d8b8ea5022733869)" = ["fish-manpage-completions"]
"fls 0.1.0 (path+file:///home/sugimoto/repos/fls)" = ["fls"]
"gprepo 0.2.0 (git+https://github.com/jtrv/gprepo#da21a52eaad162db48b6f77b77e727e6f7ee521e)" = ["gprepo"]
"grug 0.1.0 (git+https://github.com/jtrv/grug#bdc83b8316beb676cf5561c392e164a73cb11a74)" = ["grug"]
"handlr-regex 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["handlr"]
"hashgood 0.5.0 (git+https://github.com/thombles/hashgood#ecc0689d77efa0a4fbf171bfc1f80872bbee4882)" = ["hashgood"]
"hexhog 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexhog"]
"httm 0.49.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["httm"]
"huniq 2.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["huniq"]
"iching 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["iching"]
"impala 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["impala"]
"jless 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jless"]
"jql 8.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["jql"]
"kak-lsp 20.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["kak-lsp"]
"kak-popup 0.6.3-beta (path+file:///home/sugimoto/.config/kak/bundle/popup.kak)" = ["kak-popup"]
"kak-tree-sitter 3.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["kak-tree-sitter"]
"kakpipe 0.5.7 (path+file:///home/sugimoto/.config/kak/bundle/kakpipe)" = ["kakpipe"]
"kakship 0.2.9 (path+file:///home/sugimoto/.config/kak/bundle/kakship)" = ["kakship"]
"kanata 1.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["kanata"]
"ktsctl 3.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ktsctl"]
"lemmeknow 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lemmeknow"]
"licensor 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["licensor"]
"lscolors 0.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lscolors"]
"lsp-ai 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsp-ai"]
"macchina 6.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["macchina"]
"magic-wormhole-cli 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wormhole-rs"]
"markdown-oxide 0.25.9 (git+https://github.com/feel-ix-343/markdown-oxide#46ec5ca0cfdfc98c4e67395afa120cf6eb39743b)" = ["markdown-oxide"]
"mcdu 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["mcdu"]
"mise 2026.5.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["mise"]
"pay-respects 0.8.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["pay-respects"]
"protonup-rs 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["protonup-rs"]
"qrtool 0.13.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["qrtool"]
"ripdrag 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["ripdrag"]
"rkak_easymotion 0.1.0 (path+file:///home/sugimoto/.config/kak/bundle/reasymotion)" = ["rkak_easymotion"]
"rmz 3.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rmz"]
"rustscan 2.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustscan"]
"rusty-man 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-man"]
"rustywind 0.24.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustywind"]
"scaphandre 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["scaphandre"]
"sccache 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
"secli 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["secli"]
"skanuvaty 0.2.1 (git+https://github.com/Esc4iCEscEsc/skanuvaty#33a007edf5502bff6dd0583f8cf6f366d9ead11a)" = ["skanuvaty"]
"skyspell 5.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["skyspell"]
"skyspell_kak 3.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["skyspell-kak"]
"sniffglue 0.16.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["sniffglue"]
"speedtest-rs 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"suckit 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["suckit"]
"superseedr 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["superseedr"]
"syms 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["syms"]
"systemd-lsp 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["systemd-lsp"]
"t-rec 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["t-rec"]
"thesauromatic 0.0.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["thesauromatic"]
"topgrade 17.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"two_percent 0.12.18 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"vopono 0.10.16 (registry+https://github.com/rust-lang/crates.io-index)" = ["vopono"]
"waybar-module-pomodoro 0.3.0 (path+file:///home/sugimoto/repos/waybar-module-pomodoro)" = ["waybar-module-pomodoro"]
"work-break 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["work-break"]
"wthrr 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wthrr"]
"zet 2.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["zet"]
"zomerth 0.1.0 (path+file:///home/sugimoto/repos/zomerth-rs)" = ["zomerth"]
