matches:

# ENGLISH PROGRAMMING LANGUAGE

  - trigger: ",,idk"
    replace: "I don't know"

  - trigger: ",,gtg"
    replace: "This should be good to go, moving status to "

  - trigger: ",,ins"
    replace: "I'm not sure, but I can find out"

  - trigger: ",,ijrn"
    replace: "I'll join right now"

  - trigger: ",,lmc"
    replace: "Let me check"

  - trigger: ",,mtc"
    replace: "Made the change, moving to QA and passing to "

  - trigger: ",,np"
    replace: "No problem"

  - trigger: ",,tia"
    replace: "Thanks, I appreciate it"

  - trigger: ",,ty"
    replace: "Thank you"

  - trigger: ",,yw"
    replace: "You're welcome"

# DYNAMIC / SHELL

  # Print the current date
  - trigger: ",,date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ",,shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
