finder = "custom"

[custom_finder]
program = "tofi"
args = ["-c", "/home/sugimoto/.config/clipcat/tofi"]

[log]
# Emit log message to systemd-journald.
emit_journald = true
# Log level.
level = "INFO"
