# https://mise.jdx.dev/registry.html
[tools]
aichat = "latest"
biome = "latest"
bun = "latest"
cargo-binstall = "latest"
doggo = "latest"
dotenv-linter = "latest"
node = "latest"
revive = "latest"
ruby = "latest"
usage = "latest"
yazi = "latest"
zig = "latest"

[settings]
plugin_autoupdate_last_check_duration = '1 day'
env_file = '.env'
idiomatic_version_file_enable_tools = [ 'crystal', 'elixir', 'go', 'java', 'node', 'python', 'ruby', 'terraform', 'yarn' ]
experimental = true
